package com.mustafazada.fintech.dto.response;

public enum StatusCode {
    INVALID_DTO,
    ALREADY_EXIST,
    SUCCESS,
    USER_NOT_EXIST,
    BAD_CREDENTIALS,
    NOT_ACTIVE_ACCOUNT,
    INVALID_AMOUNT,
    EQUALS_ACCOUNT,
    INSUFFICIENT_BALANCE,
    ACCOUNT_NOT_EXIST,
    INVALID_TOKEN,
    NOT_TIED_USER,
    INTERNAL_ERROR
}
